export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          user_id: string;
          email: string;
          full_name: string;
          company_name: string | null;
          phone: string | null;
          role: 'client' | 'admin' | 'staff';
          avatar_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          email: string;
          full_name: string;
          company_name?: string | null;
          phone?: string | null;
          role?: 'client' | 'admin' | 'staff';
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          email?: string;
          full_name?: string;
          company_name?: string | null;
          phone?: string | null;
          role?: 'client' | 'admin' | 'staff';
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      equipment_categories: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          parent_id: string | null;
          sort_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          description?: string | null;
          parent_id?: string | null;
          sort_order?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          parent_id?: string | null;
          sort_order?: number;
          created_at?: string;
        };
      };
      equipment_items: {
        Row: {
          id: string;
          category_id: string;
          name: string;
          slug: string;
          description: string | null;
          specifications: any;
          daily_rate: number;
          weekly_rate: number | null;
          monthly_rate: number | null;
          security_deposit: number;
          quantity_available: number;
          images: string[];
          is_featured: boolean;
          is_available: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          category_id: string;
          name: string;
          slug: string;
          description?: string | null;
          specifications?: any;
          daily_rate: number;
          weekly_rate?: number | null;
          monthly_rate?: number | null;
          security_deposit?: number;
          quantity_available?: number;
          images?: string[];
          is_featured?: boolean;
          is_available?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          category_id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          specifications?: any;
          daily_rate?: number;
          weekly_rate?: number | null;
          monthly_rate?: number | null;
          security_deposit?: number;
          quantity_available?: number;
          images?: string[];
          is_featured?: boolean;
          is_available?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      bookings: {
        Row: {
          id: string;
          user_id: string;
          equipment_items: string[];
          start_date: string;
          end_date: string;
          status: 'pending' | 'confirmed' | 'in_progress' | 'completed' | 'cancelled';
          total_amount: number;
          security_deposit: number;
          special_requirements: string | null;
          delivery_address: string | null;
          contact_phone: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          equipment_items: string[];
          start_date: string;
          end_date: string;
          status?: 'pending' | 'confirmed' | 'in_progress' | 'completed' | 'cancelled';
          total_amount: number;
          security_deposit?: number;
          special_requirements?: string | null;
          delivery_address?: string | null;
          contact_phone?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          equipment_items?: string[];
          start_date?: string;
          end_date?: string;
          status?: 'pending' | 'confirmed' | 'in_progress' | 'completed' | 'cancelled';
          total_amount?: number;
          security_deposit?: number;
          special_requirements?: string | null;
          delivery_address?: string | null;
          contact_phone?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      projects: {
        Row: {
          id: string;
          title: string;
          slug: string;
          description: string | null;
          content: string | null;
          client_name: string | null;
          project_type: string;
          services_provided: string[];
          images: string[];
          video_url: string | null;
          featured_image: string | null;
          status: 'draft' | 'published' | 'featured' | 'archived';
          completion_date: string | null;
          testimonial: string | null;
          testimonial_author: string | null;
          testimonial_position: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          slug: string;
          description?: string | null;
          content?: string | null;
          client_name?: string | null;
          project_type: string;
          services_provided?: string[];
          images?: string[];
          video_url?: string | null;
          featured_image?: string | null;
          status?: 'draft' | 'published' | 'featured' | 'archived';
          completion_date?: string | null;
          testimonial?: string | null;
          testimonial_author?: string | null;
          testimonial_position?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          slug?: string;
          description?: string | null;
          content?: string | null;
          client_name?: string | null;
          project_type?: string;
          services_provided?: string[];
          images?: string[];
          video_url?: string | null;
          featured_image?: string | null;
          status?: 'draft' | 'published' | 'featured' | 'archived';
          completion_date?: string | null;
          testimonial?: string | null;
          testimonial_author?: string | null;
          testimonial_position?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      quotes: {
        Row: {
          id: string;
          user_id: string | null;
          email: string;
          full_name: string;
          company_name: string | null;
          phone: string | null;
          service_type: string;
          project_description: string;
          requirements: any;
          estimated_amount: number | null;
          status: 'draft' | 'sent' | 'approved' | 'rejected' | 'expired';
          valid_until: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          email: string;
          full_name: string;
          company_name?: string | null;
          phone?: string | null;
          service_type: string;
          project_description: string;
          requirements?: any;
          estimated_amount?: number | null;
          status?: 'draft' | 'sent' | 'approved' | 'rejected' | 'expired';
          valid_until?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          email?: string;
          full_name?: string;
          company_name?: string | null;
          phone?: string | null;
          service_type?: string;
          project_description?: string;
          requirements?: any;
          estimated_amount?: number | null;
          status?: 'draft' | 'sent' | 'approved' | 'rejected' | 'expired';
          valid_until?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      blog_posts: {
        Row: {
          id: string;
          title: string;
          slug: string;
          excerpt: string | null;
          content: string;
          featured_image: string | null;
          author_id: string;
          category: string | null;
          tags: string[];
          is_published: boolean;
          published_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          slug: string;
          excerpt?: string | null;
          content: string;
          featured_image?: string | null;
          author_id: string;
          category?: string | null;
          tags?: string[];
          is_published?: boolean;
          published_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          slug?: string;
          excerpt?: string | null;
          content?: string;
          featured_image?: string | null;
          author_id?: string;
          category?: string | null;
          tags?: string[];
          is_published?: boolean;
          published_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
  };
}